services:
  target: #victim
    container_name: target
    build:
      context: .
      dockerfile: target.dockerfile
    networks:
      - hyrule
    tty: true

  poisoner: #attacker
    container_name: poisoner
    build:
      context: .
      dockerfile: poisoner.dockerfile
    networks:
      - hyrule
    tty: true

  source: #distant ftp server
    container_name: source
    build:
      context: .
      dockerfile: source.dockerfile
    networks:
      - hyrule
    ports: 
      - "21:21"
    tty: true

networks:
  hyrule:
