services:
  source:
    container_name: source
    image: debian
    networks:
      - midgard
    tty: true
  target:
    container_name: target
    image: debian
    networks:
      - midgard
    tty: true
  poisoner:
    container_name: poisoner
    image: debian
    networks:
      - midgard
    tty: true

networks:
  midgard:
    driver: bridge